# -*- coding: utf-8 -*-
"""optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qTT-UGizW1Gd_UbUQu_3fLARPiw27Qt

### **Package and Setting**
"""

!pip -q install transformers datasets evaluate jiwer accelerate safetensors
!pip -q install torch_optimizer

import os, time, math, random, json
import numpy as np
import pandas as pd
import torch
import torch.optim as optim

from dataclasses import dataclass
from typing import Dict, List, Union, Optional

from datasets import load_dataset, Audio
import evaluate

from transformers import (
    Wav2Vec2ForCTC,
    Wav2Vec2Processor,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    set_seed,
)
import transformers
import torch_optimizer as topt

from IPython.display import Audio as IPAudio, display

"""### **DATA**

"""

from datasets import load_dataset, Audio, Dataset
import numpy as np
import pandas as pd

def duration_sec(audio_obj):
    if isinstance(audio_obj, dict) and audio_obj.get("duration") is not None:
        return float(audio_obj["duration"])
    return len(audio_obj["array"]) / audio_obj["sampling_rate"]

def take_by_hours(streaming_ds, hours=3.0, max_items=None):
    max_sec = hours * 3600.0
    total = 0.0
    rows = []
    for ex in streaming_ds:
        a = ex["audio"]
        dur = duration_sec(a)
        if total + dur > max_sec:
            break
        rows.append(ex)
        total += dur
        if max_items is not None and len(rows) >= max_items:
            break
    return Dataset.from_list(rows)

def take_n(streaming_ds, n):
    rows = []
    for i, ex in enumerate(streaming_ds):
        if i >= n:
            break
        rows.append(ex)
    return Dataset.from_list(rows)

train_stream = load_dataset("librispeech_asr", "clean", split="train.100", streaming=True) \
    .cast_column("audio", Audio(sampling_rate=16_000))

test_stream = load_dataset("librispeech_asr", "clean", split="test", streaming=True) \
    .cast_column("audio", Audio(sampling_rate=16_000))

ds_raw = {
    "train": take_by_hours(train_stream, hours=3.0),
    "test":  take_n(test_stream, 300)
}

# 초경량 "optimizer 비교" 템플릿 (Colab 생존용)
# - Wav2Vec2 대신 tiny MLP로 "훈련시간 vs 성능" 비교 구조만 먼저 검증
# - Adam / AdamW / Lion / Shampoo / Muon 모두 같은 코드로 돌아가게
# - 학습이 실제로 다른지(가중치/손실) 바로 확인 가능

!pip -q install pytorch_optimizer

import time, math, gc
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch_optimizer as topt
import pytorch_optimizer as optx

torch.manual_seed(42)
np.random.seed(42)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

# -------------------------
# 1) 초경량 toy dataset (선형 + 노이즈)
# -------------------------
N_TRAIN, N_TEST, D = 8000, 2000, 128
X = np.random.randn(N_TRAIN + N_TEST, D).astype(np.float32)
w_true = np.random.randn(D).astype(np.float32)
y = (X @ w_true + 0.5*np.random.randn(N_TRAIN + N_TEST).astype(np.float32))

# binary classification으로 변환(간단하게)
y = (y > np.median(y)).astype(np.int64)

X_train = torch.tensor(X[:N_TRAIN])
y_train = torch.tensor(y[:N_TRAIN])
X_test  = torch.tensor(X[N_TRAIN:])
y_test  = torch.tensor(y[N_TRAIN:])

train_ds = torch.utils.data.TensorDataset(X_train, y_train)
test_ds  = torch.utils.data.TensorDataset(X_test, y_test)

# -------------------------
# 2) 초경량 모델
# -------------------------
class TinyMLP(nn.Module):
    def __init__(self, d):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d, 256),
            nn.ReLU(),
            nn.Linear(256, 2),
        )
    def forward(self, x):
        return self.net(x)

def make_optimizer(name, params, lr, wd):
    name = name.lower()
    if name == "adam":   return optim.Adam(params, lr=lr, weight_decay=wd)
    if name == "adamw":  return optim.AdamW(params, lr=lr, weight_decay=wd)
    if name == "lion":   return optx.Lion(params, lr=lr, weight_decay=wd)
    if name == "shampoo":return optx.Shampoo(params, lr=lr, weight_decay=wd)
    if name == "muon":   return optx.Muon(params, lr=lr, weight_decay=wd)
    raise ValueError(name)

@torch.no_grad()
def eval_acc(model, loader):
    model.eval()
    correct, total = 0, 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        pred = logits.argmax(dim=-1)
        correct += (pred == yb).sum().item()
        total += yb.numel()
    return correct / total

def run_experiment(optimizer_name, lr, batch_size=256, max_steps=300, wd=0.0, time_budget_sec=None):
    model = TinyMLP(D).to(device)
    opt = make_optimizer(optimizer_name, model.parameters(), lr=lr, wd=wd)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=0)
    test_loader  = torch.utils.data.DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=0)

    t0 = time.time()
    steps = 0
    last_loss = None

    model.train()
    it = iter(train_loader)
    while steps < max_steps:
        if time_budget_sec is not None and (time.time() - t0) >= time_budget_sec:
            break

        try:
            xb, yb = next(it)
        except StopIteration:
            it = iter(train_loader)
            xb, yb = next(it)

        xb, yb = xb.to(device), yb.to(device)

        opt.zero_grad(set_to_none=True)
        logits = model(xb)
        loss = F.cross_entropy(logits, yb)
        loss.backward()
        opt.step()

        last_loss = float(loss.item())
        steps += 1

    runtime = time.time() - t0
    acc = eval_acc(model, test_loader)

    # "학습이 실제로 달라졌는지" 체크용: 마지막 레이어 평균
    with torch.no_grad():
        wmean = model.net[-1].weight.float().mean().item()

    # cleanup
    del model, opt
    gc.collect()
    torch.cuda.empty_cache()

    return {
        "optimizer": optimizer_name,
        "lr": lr,
        "batch_size": batch_size,
        "max_steps_req": max_steps,
        "train_steps": steps,
        "train_runtime_sec": runtime,
        "last_loss": last_loss,
        "test_acc": acc,
        "last_layer_weight_mean": wmean,
    }

# -------------------------
# 3) 초경량 스윕 (딱 최소)
# -------------------------
optimizers = ["adamw", "adam", "shampoo", "muon"]
lrs = [1e-4, 3e-4]
bs = 256

rows = []
for opt_name in optimizers:
    for lr in lrs:
        try:
            r = run_experiment(opt_name, lr=lr, batch_size=bs, max_steps=300)
            print("OK:", r)
            rows.append(r)
        except Exception as e:
            print("FAILED:", opt_name, lr, "->", repr(e))

df = pd.DataFrame(rows).sort_values(["test_acc", "train_runtime_sec"], ascending=[False, True])
df

import os, time, gc
import numpy as np
import pandas as pd
import torch
import torch.optim as optim
import pytorch_optimizer as optx

from dataclasses import dataclass
from typing import Dict, List, Union, Optional

from datasets import load_dataset, Audio
from transformers import (
    Wav2Vec2Processor,
    Wav2Vec2ForCTC,
    AutoConfig,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    set_seed,
)
import evaluate

# =============================
# 1) 기본 세팅
# =============================
set_seed(42)
torch.backends.cudnn.benchmark = True
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

# =============================
# 2) 데이터 (작게)
# =============================
ds = load_dataset("librispeech_asr", "clean", split={"train": "train.100", "test": "test"})
ds = {k: v.cast_column("audio", Audio(sampling_rate=16_000)) for k, v in ds.items()}

TRAIN_N = 1000
TEST_N  = 200

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wer_metric = evaluate.load("wer")

def prepare(batch):
    audio = batch["audio"]
    iv = processor(audio["array"], sampling_rate=16_000).input_values[0]
    batch["input_values"] = iv
    batch["input_length"] = len(iv)
    batch["labels"] = processor.tokenizer(batch["text"]).input_ids
    return batch

ds["train"] = ds["train"].shuffle(seed=42).select(range(TRAIN_N)).map(
    prepare, remove_columns=ds["train"].column_names
)
ds["test"] = ds["test"].shuffle(seed=42).select(range(TEST_N)).map(
    prepare, remove_columns=ds["test"].column_names
)

# =============================
# 3) Data Collator
# =============================
@dataclass
class DataCollatorCTCWithPadding:
    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True

    def __call__(self, features):
        input_features = [{"input_values": f["input_values"]} for f in features]
        batch = self.processor.pad(input_features, padding=True, return_tensors="pt")

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(label_features, padding=True, return_tensors="pt")

        labels = labels_batch["input_ids"].masked_fill(labels_batch["attention_mask"].ne(1), -100)
        batch["labels"] = labels
        return batch

data_collator = DataCollatorCTCWithPadding(processor)

# =============================
# 4) Optimizer 정의
# =============================
def make_optimizer(name, params, lr, wd):
    name = name.lower()
    if name == "adam":
        return optim.Adam(params, lr=lr, weight_decay=wd)
    if name == "adamw":
        return optim.AdamW(params, lr=lr, weight_decay=wd)
    if name == "lion":
        return optx.Lion(params, lr=lr, weight_decay=wd)
    if name == "shampoo":
        return optx.Shampoo(params, lr=lr, weight_decay=wd)
    raise ValueError(name)

class LossCSVCallback(TrainerCallback):
    def __init__(self, csv_path):
        self.csv_path = csv_path
        self.rows = []
        self.t0 = None

    def on_train_begin(self, args, state, control, **kwargs):
        self.t0 = time.time()

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and "loss" in logs:
            row = {
                "step": state.global_step,
                "loss": float(logs["loss"]),
                "elapsed_sec": time.time() - self.t0,
            }
            self.rows.append(row)
            pd.DataFrame(self.rows).to_csv(self.csv_path, index=False)


class OptimizerTrainer(Trainer):
    def __init__(self, optimizer_name, lr, weight_decay, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.optimizer_name = optimizer_name
        self._lr = lr
        self._wd = weight_decay

    def create_optimizer(self):
        if self.optimizer is None:
            self.optimizer = make_optimizer(
                self.optimizer_name,
                self.model.parameters(),
                lr=self._lr,
                wd=self._wd,
            )
        return self.optimizer

# =============================
# 7) 모델 초기화
# =============================
config = AutoConfig.from_pretrained("facebook/wav2vec2-base-960h")

def build_model():
    model = Wav2Vec2ForCTC.from_pretrained(
        "facebook/wav2vec2-base-960h",
        ctc_loss_reduction="mean",
        pad_token_id=processor.tokenizer.pad_token_id,
    )
    model.freeze_feature_extractor()
    return model.to(device)

# =============================
# 8) 실험 함수
# =============================
def run_experiment(opt_name, lr, batch_size=4, max_steps=200):

    model = build_model()
    outdir = f"./out_{opt_name}_lr{lr}_bs{batch_size}"
    os.makedirs(outdir, exist_ok=True)

    loss_csv = os.path.join(outdir, "train_loss.csv")

    args = TrainingArguments(
        output_dir=outdir,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        eval_strategy="steps",
        eval_steps=10**9,
        save_steps=10**9,
        logging_steps=10,
        learning_rate=lr,
        max_steps=max_steps,
        warmup_steps=10,
        fp16=torch.cuda.is_available(),
        report_to="none",
        remove_unused_columns=False,
        dataloader_num_workers=0,
        group_by_length=True,
        length_column_name="input_length",
        overwrite_output_dir=True,
    )

    trainer = OptimizerTrainer(
        optimizer_name=opt_name,
        lr=lr,
        weight_decay=0.0,
        model=model,
        args=args,
        train_dataset=ds["train"],
        eval_dataset=ds["test"],
        data_collator=data_collator,
        compute_metrics=None,
        callbacks=[LossCSVCallback(loss_csv)],
    )

    t0 = time.time()
    trainer.train()
    runtime = time.time() - t0

    # 마지막에만 WER 계산
    def compute_metrics(pred):
        pred_ids = np.argmax(pred.predictions, axis=-1)
        pred_str = processor.batch_decode(pred_ids)
        label_ids = pred.label_ids.copy()
        label_ids[label_ids == -100] = processor.tokenizer.pad_token_id
        label_str = processor.batch_decode(label_ids, group_tokens=False)
        return {"wer": wer_metric.compute(predictions=pred_str, references=label_str)}

    trainer.compute_metrics = compute_metrics
    eval_out = trainer.evaluate()

    result = {
        "optimizer": opt_name,
        "lr": lr,
        "batch_size": batch_size,
        "train_runtime_sec": runtime,
        "train_steps": trainer.state.global_step,
        "eval_wer": eval_out["eval_wer"],
        "loss_csv": loss_csv,
    }

    del trainer, model
    gc.collect()
    torch.cuda.empty_cache()

    return result

# =============================
# 9) 실행
# =============================
optimizers = ["adamw", "adam", "lion", "shampoo"]
lrs = [3e-5, 1e-4]

results = []
for opt in optimizers:
    for lr in lrs:
        try:
            r = run_experiment(opt, lr)
            print("OK:", r)
            results.append(r)
        except Exception as e:
            print("FAILED:", opt, lr, e)

df = pd.DataFrame(results)
df.to_csv("asr_optimizer_results.csv", index=False)
df

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/drive/MyDrive/wav2vec_backup
!cp -r out_fixed_steps_* /content/drive/MyDrive/wav2vec_backup/
!cp results_*.csv /content/drive/MyDrive/wav2vec_backup/

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/drive/MyDrive/full_backup

!rsync -a --progress \
  --exclude='drive' \
  /content/ \
  /content/drive/MyDrive/full_backup/

import os, time, gc, re
import numpy as np
import pandas as pd
import torch
import torch.optim as optim
import pytorch_optimizer as optx
from dataclasses import dataclass
from typing import Dict, List, Union
from datasets import load_dataset, Audio
from transformers import (
    Wav2Vec2Processor, Wav2Vec2ForCTC, AutoConfig,
    TrainingArguments, Trainer, set_seed
)
import evaluate

# 1. 초기 설정
set_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wer_metric = evaluate.load("wer")
CLEAN_CHARS = '[\,\?\.\!\-\;\:\"\[\]]'

# 2. 데이터 로드 및 전처리
ds = load_dataset("librispeech_asr", "clean", split={"train": "train.100", "test": "test"})
ds = {k: v.cast_column("audio", Audio(sampling_rate=16_000)) for k, v in ds.items()}

def prepare(batch):
    audio = batch["audio"]
    batch["input_values"] = processor(audio["array"], sampling_rate=16_000).input_values[0]
    # 모델 학습을 위해 대문자 변환 및 특수문자 제거 필수
    text = re.sub(CLEAN_CHARS, '', batch["text"].upper())
    batch["labels"] = processor.tokenizer(text).input_ids
    return batch

train_ds = ds["train"].shuffle(seed=42).select(range(1000)).map(prepare, remove_columns=ds["train"].column_names)
test_ds = ds["test"].shuffle(seed=42).select(range(200)).map(prepare, remove_columns=ds["test"].column_names)

# 3. Data Collator
@dataclass
class DataCollatorCTCWithPadding:
    processor: Wav2Vec2Processor
    def __call__(self, features):
        iv = [{"input_values": f["input_values"]} for f in features]
        batch = self.processor.pad(iv, padding=True, return_tensors="pt")
        labels = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(labels, padding=True, return_tensors="pt")
        batch["labels"] = labels_batch["input_ids"].masked_fill(labels_batch["attention_mask"].ne(1), -100)
        return batch

data_collator = DataCollatorCTCWithPadding(processor)

# 4. Optimizer 생성 함수
def get_opt(name, params, lr):
    name = name.lower()
    if name == "adam": return optim.Adam(params, lr=lr)
    if name == "adamw": return optim.AdamW(params, lr=lr, weight_decay=0.01)
    if name == "lion": return optx.Lion(params, lr=lr, weight_decay=0.01)
    raise ValueError(name)

# 5. 실험 실행 함수
def run_exp(opt_name, lr, steps=200):
    model = Wav2Vec2ForCTC.from_pretrained(
        "facebook/wav2vec2-base-960h",
        ctc_loss_reduction="mean",
        pad_token_id=processor.tokenizer.pad_token_id
    ).to(device)
    model.freeze_feature_extractor()

    optimizer = get_opt(opt_name, model.parameters(), lr)

    args = TrainingArguments(
        output_dir=f"./{opt_name}_{lr}",
        per_device_train_batch_size=4,
        max_steps=steps,
        logging_steps=10,
        fp16=True,
        push_to_hub=False,
        report_to="none"
    )

    def compute_metrics(pred):
        p_ids = np.argmax(pred.predictions, axis=-1)
        p_str = processor.batch_decode(p_ids)
        l_ids = pred.label_ids
        l_ids[l_ids == -100] = processor.tokenizer.pad_token_id
        l_str = processor.batch_decode(l_ids, group_tokens=False)
        return {"wer": wer_metric.compute(predictions=p_str, references=l_str)}

    trainer = Trainer(
        model=model, args=args, train_dataset=train_ds, eval_dataset=test_ds,
        data_collator=data_collator, compute_metrics=compute_metrics,
        optimizers=(optimizer, None)
    )

    trainer.train()
    res = trainer.evaluate()

    del trainer, model, optimizer
    gc.collect(); torch.cuda.empty_cache()
    return {"opt": opt_name, "lr": lr, "wer": res["eval_wer"]}

# 6. 메인 실행
opts = ["adamw", "adam", "lion"]
lrs = [3e-5, 1e-4]
results = [run_exp(o, l) for o in opts for l in lrs]

df = pd.DataFrame(results)
print(df)
df.to_csv("asr_results.csv", index=False)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

MODEL_NAME = "facebook/wav2vec2-base"

OUTPUT_ROOT = "./asr_runs"
RESULT_CSV = "asr_results.csv"

MODE = "fixed_steps"
MAX_STEPS = 600
TRAIN_SUBSET = 1000
TEST_SUBSET = 200

# OPTIMIZERS = ["adam", "adamw", "shampoo"]
OPTIMIZERS = ["lion"]

LRS = [1e-5, 3e-5, 1e-4]
BATCH_SIZES = [8, 16]
GRAD_ACCUM = 1
WEIGHT_DECAY = 0.1

CLEAN_CHARS = r"[\,\?\.\!\-\;\:\"\[\]\']"

os.makedirs(OUTPUT_ROOT, exist_ok=True)

print(f"DEVICE: {DEVICE}")
print(f"MODEL_NAME: {MODEL_NAME}")

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wer_metric = evaluate.load("wer")


print("Loading dataset...")
ds = load_dataset(
    "librispeech_asr",
    "clean",
    split={"train": "train.100", "test": "test"},
)

ds = {
    k: v.cast_column("audio", Audio(sampling_rate=16_000))
    for k, v in ds.items()
}


def normalize_text(text: str) -> str:
    text = re.sub(CLEAN_CHARS, "", text.upper())
    text = re.sub(r"\s+", " ", text).strip()
    return text


def prepare(batch):
    audio = batch["audio"]

    batch["input_values"] = processor(
        audio["array"],
        sampling_rate=16_000
    ).input_values[0]

    text = normalize_text(batch["text"])
    batch["labels"] = processor.tokenizer(text).input_ids
    return batch


print("Preprocessing dataset...")
train_ds = (
    ds["train"]
    .shuffle(seed=42)
    .select(range(TRAIN_SUBSET))
    .map(prepare, remove_columns=ds["train"].column_names)
)

test_ds = (
    ds["test"]
    .shuffle(seed=42)
    .select(range(TEST_SUBSET))
    .map(prepare, remove_columns=ds["test"].column_names)
)


@dataclass
class DataCollatorCTCWithPadding:
    processor: Wav2Vec2Processor

    def __call__(self, features):
        input_features = [{"input_values": f["input_values"]} for f in features]
        batch = self.processor.pad(
            input_features,
            padding=True,
            return_tensors="pt"
        )

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(
            label_features,
            padding=True,
            return_tensors="pt"
        )

        labels = labels_batch["input_ids"].masked_fill(
            labels_batch["attention_mask"].ne(1),
            -100
        )
        batch["labels"] = labels
        return batch


data_collator = DataCollatorCTCWithPadding(processor=processor)


def get_optimizer(name, model, lr, weight_decay):
    name = name.lower()

    if name == "adam":
        return optim.Adam(
            model.parameters(),
            lr=lr,
            weight_decay=weight_decay
        )

    if name == "adamw":
        return optim.AdamW(
            model.parameters(),
            lr=lr,
            weight_decay=weight_decay
        )

    if name == "shampoo":
        if not hasattr(optx, "Shampoo"):
            raise AttributeError(
                "pytorch_optimizer에 Shampoo가 없습니다. "
                "설치 버전을 확인하세요."
            )
        return optx.Shampoo(
            model.parameters(),
            lr=lr,
            weight_decay=weight_decay
        )

    raise ValueError(f"Unknown optimizer: {name}")


def compute_metrics(pred):
    pred_ids = np.argmax(pred.predictions, axis=-1)
    pred_str = processor.batch_decode(pred_ids)

    label_ids = pred.label_ids.copy()
    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id
    label_str = processor.batch_decode(label_ids, group_tokens=False)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)
    return {"wer": wer}


def build_model():
    model = Wav2Vec2ForCTC.from_pretrained(
        MODEL_NAME,
        ctc_loss_reduction="mean",
        pad_token_id=processor.tokenizer.pad_token_id,
        vocab_size=len(processor.tokenizer),
        ignore_mismatched_sizes=True,
    )
    if hasattr(model, "freeze_feature_encoder"):
        model.freeze_feature_encoder()
    elif hasattr(model, "freeze_feature_extractor"):
        model.freeze_feature_extractor()

    return model.to(DEVICE)


def run_exp(optimizer_name, lr, batch_size, grad_accum, weight_decay, max_steps):
    run_name = (
        f"{MODE}_{optimizer_name}_lr{lr}_bs{batch_size}"
        f"_ga{grad_accum}_wd{weight_decay}"
    )
    output_dir = os.path.join(OUTPUT_ROOT, run_name)

    print("\n" + "=" * 80)
    print(f"[RUN] {run_name}")

    model = build_model()

    optimizer = get_optimizer(
        name=optimizer_name,
        model=model,
        lr=lr,
        weight_decay=weight_decay
    )

    training_args = TrainingArguments(
        output_dir=output_dir,
        max_steps=max_steps,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=grad_accum,
        logging_steps=10,
        eval_strategy="no",
        save_strategy="no",
        report_to="none",
        push_to_hub=False,
        fp16=torch.cuda.is_available(),
        bf16=False,
        dataloader_num_workers=4,
        remove_unused_columns=False,
        seed=42,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=test_ds,
        data_collator=data_collator,
        processing_class=processor,
        compute_metrics=compute_metrics,
        optimizers=(optimizer, None),
    )

    start = time.time()
    trainer.train()
    train_runtime_sec = round(time.time() - start, 1)

    eval_res = trainer.evaluate()

    row = {
        "mode": MODE,
        "optimizer": optimizer_name,
        "lr": lr,
        "batch_size": batch_size,
        "grad_accum": grad_accum,
        "weight_decay": weight_decay,
        "train_runtime_sec": train_runtime_sec,
        "train_steps": max_steps,
        "eval_wer": round(eval_res["eval_wer"], 4),
    }

    print("[RESULT]", row)

    del trainer, model, optimizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return row


# =========================
# 8) 전체 실행
# =========================
def main():
    results = []

    for batch_size in BATCH_SIZES:
        for optimizer_name in OPTIMIZERS:
            for lr in LRS:
                try:
                    row = run_exp(
                        optimizer_name=optimizer_name,
                        lr=lr,
                        batch_size=batch_size,
                        grad_accum=GRAD_ACCUM,
                        weight_decay=WEIGHT_DECAY,
                        max_steps=MAX_STEPS,
                    )
                    results.append(row)

                except Exception as e:
                    print(f"[ERROR] optimizer={optimizer_name}, lr={lr}, bs={batch_size}")
                    print(e)

                    results.append({
                        "mode": MODE,
                        "optimizer": optimizer_name,
                        "lr": lr,
                        "batch_size": batch_size,
                        "grad_accum": GRAD_ACCUM,
                        "weight_decay": WEIGHT_DECAY,
                        "train_runtime_sec": None,
                        "train_steps": MAX_STEPS,
                        "eval_wer": None,
                    })

                pd.DataFrame(results).to_csv(RESULT_CSV, index=False)

    df = pd.DataFrame(results)
    print("\nFinal results")
    print(df.sort_values(["batch_size", "optimizer", "lr"], na_position="last"))
    df.to_csv(RESULT_CSV, index=False)


if __name__ == "__main__":
    main()